version: '3.8'

services:
  app:
    build:
      context: .  # Current directory, which should contain the Dockerfile
    container_name: data_ingestion_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/metrics_db
    volumes:
      - ./app:/app
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
